name: next lint

on:
  push:
  pull_request:

jobs:
  build:
    name: next lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install depenancies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend
          install-command: yarn --frozen-lockfile

      - name: next lint
        uses: ./
        with:
          working-directory: frontend
          command: npx next lint